Repository apollographql/apollo-server, pull requests merged in 2018-08, with the labels that each got.

#1430 Updated Deployment Guides
  docs/source/deployment/heroku.md
  docs/source/deployment/lambda.md
  docs/source/deployment/now.md
  docs/source/images/deployment/heroku/heroku-github-instructions.png
  docs/source/images/deployment/zeit/now-github-permissions.png
Labels: docs

#1384 Allow additional Hapi route options to be passed
  CHANGELOG.md
  packages/apollo-server-hapi/src/ApolloServer.ts
  packages/apollo-server-hapi/src/__tests__/ApolloServer.test.ts
Labels: feature

#1368 Migration docs for schema as object
  docs/source/migration-two-dot.md
Labels: docs

#1495 Fixed GraphQL Playground with custom configuration in production.
  CHANGELOG.md
  packages/apollo-server-core/src/playground.ts
  packages/apollo-server-express/src/__tests__/ApolloServer.test.ts
Labels: bug

#1446 Implementation of Apollo Server 2 for Google Cloud Functions
  CHANGELOG.md
  packages/apollo-server-cloud-function/.npmignore
  packages/apollo-server-cloud-function/README.md
  packages/apollo-server-cloud-function/package.json
  packages/apollo-server-cloud-function/src/ApolloServer.ts
  packages/apollo-server-cloud-function/src/googleCloudApollo.test.ts
  packages/apollo-server-cloud-function/src/googleCloudApollo.ts
  packages/apollo-server-cloud-function/src/index.ts
  packages/apollo-server-cloud-function/tsconfig.json
Labels: feature
