Repository apollographql/apollo-server, pull requests merged in 2020-04, with the labels that each got.

#3926 feat(lambda) File uploads
  CHANGELOG.md
  package-lock.json
  package.json
  packages/apollo-server-cloud-functions/src/__tests__/googleCloudApollo.test.ts
  packages/apollo-server-integration-testsuite/src/index.ts
  packages/apollo-server-lambda/src/ApolloServer.ts
  packages/apollo-server-lambda/src/__tests__/lambdaApollo.test.ts
  packages/apollo-server-lambda/src/lambdaApollo.ts
Labels: 🖇️ lambda

#3968 Add async-graphql to Federation third-party support
  docs/source/federation/other-servers.md
Labels: :memo: documentation, 👩‍🚀 federation

#3985 Use named types for the "DidEnd" hooks.
  packages/apollo-server-plugin-base/src/index.ts
Labels: 🧬 typings

#3989 chore: Convert `schemaHash` from `string` to a faux-paque type.
  packages/apollo-engine-reporting/src/agent.ts
  packages/apollo-engine-reporting/src/extension.ts
  packages/apollo-server-core/src/ApolloServer.ts
  packages/apollo-server-core/src/utils/schemaHash.ts
  packages/apollo-server-types/src/index.ts
Labels: 🧬 typings

#3990 Introduce an internal plugin test harness to facilitate plugin testing.
  packages/apollo-server-core/src/utils/pluginTestHarness.ts
Labels: 🧪 testing

#3929 Update metrics.md typo - "exected" becomes "executed"
  docs/source/federation/metrics.md
Labels: :memo: documentation

#3936 docs: Fix typo on implementing services
  docs/source/federation/implementing-services.mdx
Labels: :memo: documentation

#4014 docs: kill two typos in one line
  docs/source/api/graphql-tools.md
Labels: :memo: documentation

#3950 docs: Add comma to fix syntax error in "plugins"
  docs/source/integrations/plugins.md
Labels: :memo: documentation

#3927 fix(gateway): add missing `apollo-server-errors` runtime dependency.
  package-lock.json
  packages/apollo-gateway/CHANGELOG.md
  packages/apollo-gateway/package.json
Labels: 👩‍🚀 federation

#3709 docs: Note about using subscriptions with EventEmitter at scale.
  docs/source/data/subscriptions.md
Labels: 🧬 subscriptions

#2314 feat(subscriptions): enable passing `WebSocket.Server` instead of `HttpServer`.
  CHANGELOG.md
  packages/apollo-server-core/src/ApolloServer.ts
Labels: 🧬 subscriptions

#3566 docs: Update comment for uploads.
  docs/source/data/file-uploads.md
Labels: :memo: documentation, 🧬 uploads

#3659 docs(lambda): Update Node.js version in README.md
  packages/apollo-server-lambda/README.md
Labels: :memo: documentation, 🖇️ lambda

#3673 docs: Clarify what passing `app` to `applyMiddleware` does.
  docs/source/integrations/middleware.md
Labels: :memo: documentation

#4018 feat(gateway): relocate downstream query construction
  packages/apollo-gateway/CHANGELOG.md
  packages/apollo-gateway/src/QueryPlan.ts
  packages/apollo-gateway/src/buildQueryPlan.ts
  packages/apollo-gateway/src/executeQueryPlan.ts
Labels: 👩‍🚀 federation

#3777 docs: add `graphql-java-federation` to server implementation list
  docs/source/federation/other-servers.md
Labels: :memo: documentation, 👩‍🚀 federation

#4038 Add caliban to the list of federation support
  docs/source/federation/other-servers.md
Labels: :memo: documentation, 👩‍🚀 federation

#4031 Drop support for Node.js 8 and 10 in Gateway.
  packages/apollo-gateway/CHANGELOG.md
  packages/apollo-gateway/jest.config.js
  packages/apollo-gateway/package.json
  packages/apollo-gateway/tsconfig.json
Labels: 🍳 breaking-change, 👩‍🚀 federation, 💬 discussion
