Repository apollographql/apollo-server, pull requests merged in 2020-05, with the labels that each got.

#4076 feat(plugins): Intro. `didResolveSource` to indicate availability of "source".
  docs/source/integrations/plugins.md
  packages/apollo-server-core/src/__tests__/runQuery.test.ts
  packages/apollo-server-core/src/requestPipeline.ts
  packages/apollo-server-integration-testsuite/src/index.ts
  packages/apollo-server-plugin-base/src/index.ts
  packages/apollo-server-types/src/index.ts
Labels: 🔌 plugins

#4071 fix(gateway): Correctly handle unions with nested conditions that have no `possibleTypes`
  packages/apollo-gateway/CHANGELOG.md
  packages/apollo-gateway/src/__tests__/buildQueryPlan.test.ts
  packages/apollo-gateway/src/buildQueryPlan.ts
Labels: 👩‍🚀 federation

#3988 Add support for `willResolveField` and corresponding end handler.
  docs/source/integrations/plugins.md
  packages/apollo-engine-reporting/src/agent.ts
  packages/apollo-engine-reporting/src/extension.ts
  packages/apollo-gateway/src/executeQueryPlan.ts
  packages/apollo-gateway/src/index.ts
  packages/apollo-server-core/src/ApolloServer.ts
  packages/apollo-server-core/src/__tests__/runQuery.test.ts
  packages/apollo-server-core/src/requestPipeline.ts
  packages/apollo-server-core/src/utils/dispatcher.ts
  packages/apollo-server-core/src/utils/pluginTestHarness.ts
  packages/apollo-server-core/src/utils/schemaHash.ts
  packages/apollo-server-core/src/utils/schemaInstrumentation.ts
  packages/apollo-server-integration-testsuite/src/index.ts
  packages/apollo-server-plugin-base/src/index.ts
  packages/apollo-server-types/src/index.ts
Labels: 🔌 plugins

#3996 Place `schema` and `schemaHash` on the `GraphQLRequestContext`.
  packages/apollo-server-core/src/ApolloServer.ts
  packages/apollo-server-core/src/__tests__/runQuery.test.ts
  packages/apollo-server-core/src/graphqlOptions.ts
  packages/apollo-server-core/src/runHttpQuery.ts
  packages/apollo-server-core/src/utils/pluginTestHarness.ts
  packages/apollo-server-types/src/index.ts
Labels: 🔌 plugins

#3991 refactor: Introduce "tracing" plugin and switch request pipeline to use it.
  CHANGELOG.md
  package-lock.json
  packages/apollo-server-core/src/ApolloServer.ts
  packages/apollo-server-core/src/requestPipeline.ts
  packages/apollo-tracing/README.md
  packages/apollo-tracing/package.json
  packages/apollo-tracing/src/index.ts
  packages/apollo-tracing/tsconfig.json
Labels: 🔌 plugins, 🧬 graphql-extensions

#3997 refactor: Replace "cache-control" extension with plugin.
  package-lock.json
  packages/apollo-cache-control/package.json
  packages/apollo-cache-control/src/__tests__/cacheControlExtension.test.ts
  packages/apollo-cache-control/src/__tests__/cacheControlPlugin.test.ts
  packages/apollo-cache-control/src/__tests__/collectCacheControlHints.ts
  packages/apollo-cache-control/src/index.ts
  packages/apollo-cache-control/tsconfig.json
  packages/apollo-server-core/src/ApolloServer.ts
  packages/apollo-server-core/src/requestPipeline.ts
  packages/apollo-server-core/src/runHttpQuery.ts
Labels: 🔌 plugins, 🧬 graphql-extensions

#3998 refactor: Graph Manager (Engine) reporting "extensions" become "plugins".
  CHANGELOG.md
  package-lock.json
  packages/apollo-engine-reporting/package.json
  packages/apollo-engine-reporting/src/__tests__/plugin.test.ts
  packages/apollo-engine-reporting/src/agent.ts
  packages/apollo-engine-reporting/src/extension.ts
  packages/apollo-engine-reporting/src/federatedExtension.ts
  packages/apollo-engine-reporting/src/federatedPlugin.ts
  packages/apollo-engine-reporting/src/index.ts
  packages/apollo-engine-reporting/src/plugin.ts
  packages/apollo-engine-reporting/src/treeBuilder.ts
  packages/apollo-engine-reporting/tsconfig.json
  packages/apollo-server-core/src/ApolloServer.ts
  packages/apollo-server-core/src/requestPipeline.ts
  packages/apollo-server-types/src/index.ts
Labels: 🔌 plugins, 🧬 graphql-extensions

#4135 Add deprecation warnings for `GraphQLExtension` usage.
  packages/apollo-server-core/src/__tests__/runQuery.test.ts
  packages/apollo-server-core/src/requestPipeline.ts
Labels: 🧬 graphql-extensions

#4084 feat: Automatic schema reporting to Apollo Graph Manager
  package-lock.json
  package.json
  packages/apollo-engine-reporting-protobuf/src/reports.proto
  packages/apollo-engine-reporting/package.json
  packages/apollo-engine-reporting/src/__tests__/agent.test.ts
  packages/apollo-engine-reporting/src/__tests__/plugin.test.ts
  packages/apollo-engine-reporting/src/__tests__/schemaReporter.test.ts
  packages/apollo-engine-reporting/src/agent.ts
  packages/apollo-engine-reporting/src/plugin.ts
  packages/apollo-engine-reporting/src/reportingOperationTypes.ts
  packages/apollo-engine-reporting/src/schemaReporter.ts
  packages/apollo-server-core/src/utils/pluginTestHarness.ts
  packages/apollo-server-integration-testsuite/src/ApolloServer.ts
Labels: 🧮 metrics

#4064 fix(gateway): merge selection sets of `@requires` fields
  packages/apollo-gateway/CHANGELOG.md
  packages/apollo-gateway/src/FieldSet.ts
  packages/apollo-gateway/src/__tests__/integration/complex-key.test.ts
  packages/apollo-gateway/src/__tests__/integration/requires.test.ts
  packages/apollo-gateway/src/utilities/array.ts
Labels: :beetle: bug, 👩‍🚀 federation
