Repository apollographql/apollo-server, pull requests merged in 2020-03, with the labels that each got.

#3763 Release 2.11.0
  CHANGELOG.md
  docs/source/api/apollo-gateway.mdx
  docs/source/federation/implementing.md
  package-lock.json
  packages/apollo-cache-control/package.json
  packages/apollo-datasource-rest/package.json
  packages/apollo-engine-reporting/package.json
  packages/apollo-engine-reporting/src/__tests__/extension.test.ts
  packages/apollo-federation/CHANGELOG.md
  packages/apollo-federation/jest.config.js
  packages/apollo-federation/package.json
  packages/apollo-gateway/CHANGELOG.md
  packages/apollo-gateway/jest.config.js
  packages/apollo-gateway/package.json
  packages/apollo-gateway/src/QueryPlan.ts
  packages/apollo-gateway/src/__tests__/buildQueryPlan.test.ts
  packages/apollo-gateway/src/__tests__/integration/networkRequests.test.ts
  packages/apollo-gateway/src/__tests__/integration/nockMocks.ts
  packages/apollo-gateway/src/__tests__/matchers/toCallService.ts
  packages/apollo-gateway/src/__tests__/matchers/toHaveBeenCalledBefore.ts
  packages/apollo-gateway/src/__tests__/matchers/toHaveFetched.ts
  packages/apollo-gateway/src/__tests__/matchers/toMatchAST.ts
  packages/apollo-gateway/src/buildQueryPlan.ts
  packages/apollo-gateway/src/cache.ts
  packages/apollo-gateway/src/cachedFetcher.ts
  packages/apollo-gateway/src/datasources/RemoteGraphQLDataSource.ts
  packages/apollo-gateway/src/datasources/__tests__/RemoteGraphQLDataSource.test.ts
  packages/apollo-gateway/src/executeQueryPlan.ts
  packages/apollo-gateway/src/index.ts
  packages/apollo-gateway/src/loadServicesFromStorage.ts
  packages/apollo-gateway/src/make-fetch-happen.d.ts
  packages/apollo-gateway/src/snapshotSerializers/queryPlanSerializer.ts
  packages/apollo-server-azure-functions/package.json
  packages/apollo-server-cloud-functions/package.json
  packages/apollo-server-cloudflare/package.json
  packages/apollo-server-core/package.json
  packages/apollo-server-errors/package.json
  packages/apollo-server-express/package.json
  packages/apollo-server-fastify/package.json
  packages/apollo-server-hapi/package.json
  packages/apollo-server-integration-testsuite/package.json
  packages/apollo-server-koa/package.json
  packages/apollo-server-lambda/package.json
  packages/apollo-server-micro/package.json
  packages/apollo-server-plugin-base/package.json
  packages/apollo-server-plugin-response-cache/package.json
  packages/apollo-server-testing/package.json
  packages/apollo-server-types/package.json
  packages/apollo-server/package.json
  packages/apollo-tracing/package.json
  packages/graphql-extensions/package.json
Labels: 🏗 release

#3867 Fail to compose when a service's federated SDL cannot be retrieved.
  packages/apollo-gateway/CHANGELOG.md
  packages/apollo-gateway/src/__tests__/loadServicesFromRemoteEndpoint.test.ts
  packages/apollo-gateway/src/loadServicesFromRemoteEndpoint.ts
Labels: 🍳 breaking-change, 👩‍🚀 federation

#3886 docs: Document new `fetcher` on `@apollo/gateway`.
  docs/source/api/apollo-gateway.mdx
Labels: :memo: documentation

#3865 Fix Typescript generic typing for datasource contexts
  packages/apollo-gateway/CHANGELOG.md
  packages/apollo-gateway/src/datasources/LocalGraphQLDataSource.ts
  packages/apollo-gateway/src/datasources/RemoteGraphQLDataSource.ts
  packages/apollo-gateway/src/datasources/types.ts
  packages/apollo-gateway/src/executeQueryPlan.ts
Labels: 👩‍🚀 federation

#3836 Gateway: retry logic for requests to GCS
  packages/apollo-gateway/CHANGELOG.md
  packages/apollo-gateway/src/__tests__/integration/networkRequests.test.ts
  packages/apollo-gateway/src/index.ts
Labels: 👩‍🚀 federation
