Repository apollographql/apollo-server, pull requests merged in 2021-07, with the labels that each got.

#5406 docs: update subscriptions docs for v3
  docs/source/data/subscriptions.mdx
  docs/source/migration.mdx
Labels: :memo: documentation

#5420 Edits to union/interface docs
  docs/source/schema/unions-interfaces.md
Labels: :memo: documentation

#5508 feat(UserInputError): handle unhandled errors.
  CHANGELOG.md
  packages/apollo-server-core/src/requestPipeline.ts
  packages/apollo-server-integration-testsuite/src/ApolloServer.ts
Labels: 🤏 small-effort

#5187 apollo-server-core: Update schema reporting plugin to support gateways
  CHANGELOG.md
  docs/source/integrations/plugins-event-reference.md
  docs/source/integrations/plugins.md
  docs/source/migration.mdx
  packages/apollo-server-core/src/ApolloServer.ts
  packages/apollo-server-core/src/plugin/schemaReporting/index.ts
  packages/apollo-server-core/src/types.ts
  packages/apollo-server-core/src/utils/schemaManager.ts
  packages/apollo-server-integration-testsuite/src/ApolloServer.ts
  packages/apollo-server-plugin-base/src/index.ts
  packages/apollo-server-types/src/index.ts
Labels: 👩‍🚀 federation, 📡 schema-reporting, 🦾 large-effort

#5498 Inline and improve the `stoppable` package
  package-lock.json
  package.json
  packages/apollo-server/package.json
  packages/apollo-server/src/__tests__/stoppable.test.ts
  packages/apollo-server/src/__tests__/stoppable/fixture.cert
  packages/apollo-server/src/__tests__/stoppable/fixture.key
  packages/apollo-server/src/__tests__/stoppable/server.js
  packages/apollo-server/src/index.ts
  packages/apollo-server/src/stoppable.ts
Labels: 💪 medium-effort

#5538 Release 3.1.0
  CHANGELOG.md
  package-lock.json
  package.json
  packages/apollo-datasource-rest/package.json
  packages/apollo-datasource/package.json
  packages/apollo-server-azure-functions/package.json
  packages/apollo-server-cache-memcached/package.json
  packages/apollo-server-cache-redis/package.json
  packages/apollo-server-cloud-functions/package.json
  packages/apollo-server-cloudflare/package.json
  packages/apollo-server-core/package.json
  packages/apollo-server-core/src/ApolloServer.ts
  packages/apollo-server-core/src/plugin/cacheControl/index.ts
  packages/apollo-server-core/src/types.ts
  packages/apollo-server-core/src/utils/schemaManager.ts
  packages/apollo-server-env/package.json
  packages/apollo-server-express/package.json
  packages/apollo-server-fastify/package.json
  packages/apollo-server-hapi/package.json
  packages/apollo-server-integration-testsuite/package.json
  packages/apollo-server-integration-testsuite/src/ApolloServer.ts
  packages/apollo-server-koa/package.json
  packages/apollo-server-lambda/package.json
  packages/apollo-server-micro/package.json
  packages/apollo-server-plugin-base/package.json
  packages/apollo-server-plugin-operation-registry/package.json
  packages/apollo-server-plugin-operation-registry/src/index.ts
  packages/apollo-server-plugin-response-cache/package.json
  packages/apollo-server-plugin-response-cache/src/index.ts
  packages/apollo-server-types/package.json
  packages/apollo-server/package.json
  packages/apollo-server/src/__tests__/stoppable.test.ts
  packages/apollo-server/src/__tests__/stoppable/fixture.cert
  packages/apollo-server/src/__tests__/stoppable/fixture.key
  packages/apollo-server/src/__tests__/stoppable/server.js
  packages/apollo-server/src/index.ts
  packages/apollo-server/src/stoppable.ts
Labels: 📦 release

#5555 docs: Fix subscriptions + context documentation
  docs/source/data/subscriptions.mdx
  docs/source/migration.mdx
Labels: 2021-07, :memo: documentation, 🤏 small-effort
